FROM node:16

WORKDIR /app

# Копируем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальной код
COPY . .

# Открываем порт 3000 для браузера
EXPOSE 3000

# Запускаем сервер разработки
CMD ["npm", "start"]