# Stage 1: build React
FROM node:16 AS build
WORKDIR /app

# Передаем аргументы сборки
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: serve with Nginx
FROM nginx:alpine

# Копируем собранное приложение
COPY --from=build /app/build /usr/share/nginx/html

# Копируем шаблон конфига nginx
COPY ./nginx/conf.d/default.conf.template /etc/nginx/conf.d/default.conf.template

# Скрипт для подстановки переменных при старте
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

EXPOSE 80 443

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]