# Stage 1: build React
FROM node:16 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install --no-fund --no-audit

COPY . .
RUN npm run build

# Stage 2: serve with Nginx
FROM nginx:stable-alpine

# Копируем собранное приложение
COPY --from=build /app/build /usr/share/nginx/html

# Копируем конфиг nginx
COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

# Проверяем, что конфиг скопировался
RUN cat /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]