services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: react-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge