services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend

    restart: always
    command: server
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: family_shop
      REDIS_URL: redis://redis:6379
      SESSION_SECRET: super_secret_key
      NODE_ENV: production

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health/"]
      interval: 10s
      timeout: 5s
      retries: 5

    stop_grace_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend

    restart: always

    ports:
      - "80:80"

    depends_on:
      backend:
        condition: service_healthy

  db:
    image: postgres:15-alpine

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: family_shop

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

    container_name: redis

    restart: always

volumes:
  postgres_data: