FROM python:3.11-slim

WORKDIR /app

# Зависимости для работы с Postgres
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Если manage.py уже создан, эта команда запустит сервер
CMD ["python", "manage.py", "runserver", "0.0.0.0:5000"]