FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# =====================
# RUN MIGRATIONS + SEED
# =====================
CMD ["sh", "-c", "\
    python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py seed && \
    python manage.py createsuperuser_if_not_exists && \
    python manage.py runserver 0.0.0.0:5000 \
"]