FROM python:3.11-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    wget

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["sh", "-c", "\
    python manage.py migrate && \
    python manage.py seed && \
    python manage.py createsuperuser_if_not_exists && \
    gunicorn core.wsgi:application \
        --bind 0.0.0.0:5000 \
        --workers 2 \
        --worker-class gevent \
        --timeout 30 \
        --graceful-timeout 30 \
        --keep-alive 5 \
    "]
