# Generated by Django 5.2.14 on 2026-05-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_groupcartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupCartItem',
        ),
    ]
